# Generated by Django 4.2.7 on 2023-11-25 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='spent',
            name='name',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spent',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spents.category'),
            preserve_default=False,
        ),
    ]
