# Generated by Django 4.2.7 on 2023-11-25 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spents', '0002_category_spent_name_spent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spents.category'),
        ),
    ]
