# Generated by Django 4.2.7 on 2023-11-25 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spents', '0002_earncategory_earn'),
    ]

    operations = [
        migrations.AddField(
            model_name='earn',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earn',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spents.earncategory'),
        ),
        migrations.AlterField(
            model_name='spent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spents.spentcategory'),
        ),
    ]
