# Generated by Django 4.2.7 on 2023-11-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spents', '0003_earn_date_spent_date_alter_earn_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earn',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spent',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
