# Generated by Django 4.2.7 on 2023-11-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spents', '0005_account_alter_earn_date_alter_earn_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='total',
            new_name='total_dollars',
        ),
        migrations.RenameField(
            model_name='spent',
            old_name='money',
            new_name='dollars',
        ),
        migrations.AddField(
            model_name='account',
            name='currency_dollars',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='total_pesos',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='earn',
            name='pesos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spent',
            name='pesos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
