# Generated by Django 4.2.7 on 2023-11-29 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spents', '0006_rename_total_account_total_dollars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='total_pesos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='spent',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spents.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spent',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollars', models.FloatField()),
                ('buy_at', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spents.account')),
            ],
        ),
    ]
