# Generated by Django 4.2.7 on 2023-12-03 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spents', '0009_rename_money_earn_dollars_earn_in_dollar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earn',
            name='in_cash',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spent',
            name='in_cash',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcash',
            name='earn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spents.earn'),
        ),
    ]
