# Generated by Django 5.0 on 2023-12-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spents', '0010_earn_in_cash_spent_in_cash_alter_subcash_earn'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='in_cash',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
